package com.mobiapps360.LearnClockTime;

import java.util.ArrayList;
import java.util.List;

public class Constant {


    String sourceString = "➤ This is a " + "<b>" + "clock dial" + "</b> " + ".";   //"<b>" + "uuusu" + "</b> " + "sheetal";
//    List<String> learnClockAnimation_array = new ArrayList<String>();
//    learnClockAnimation_array.add(sourceString);
public static int xx = 9;
    public static String[] learnClockAnimation_array= {"➤ This is a " + "<b>" + "clock dial" + "</b>" +"."+"<br/><br/>➤ There are three hands, "+ "<b>" + "hour hand" + "</b>" +", "+"<b>" + "minute hand" + "</b>" +" and "+"<b>" + "second hand" + "</b>" + " on the face of a clock.","➤ This is an " + "<b>"+ "hour hand"+ "</b>"+"." + "<br/><br/>➤ The hour hand is a "+"<b>"+"small"+"</b>"+ " hand on a clock which shows " +"<b>"+ "hours"+"</b>"+"." + "<br/><br/>➤ When an hour hand completes " + "<b>" + "24 hours" + "</b>" + ", it's called "+ "<b>" +  "1 day" + "</b>" + ".","➤ This is a " + "<b>" +"minute hand"+ "</b>"+ "." +"<br/><br/>➤ The minute hand is the "+ "<b>" + "long" + "</b>" +" hand on a clock which shows " + "<b>" + "minutes" + "</b>" + "."+"<br/><br/>➤ When a minute hand completes "+"<b>"+"60 minutes"+"</b>" + ", it's called " + "<b>" + "1 hour" + "</b>" + "."," ➤ This is a "+ "<b>" + "second hand" + "</b>" + " on a clock which shows " +"<b>"+ "seconds"+"</b>"+"."+"<br/><br/>➤ When the second hand completes "+"<b>"+"60 seconds"+"</b>"+", it's called "+"<b>"+"1 minute"+"</b>"+"."," ➤ " + "When the " + "<b>" +"minute hand" +"</b>"+" is at the top of the clock "+"<b>"+"at 12"+"</b>"+", use the phrase "+"<b>"+"O'clock"+"</b>"+".","➤ Use the phrase " +"<b>"+ "past" + "</b>" + " when the minute hand completes between "+"<b>"+"one to 30 minutes" +"</b>"+" on the dial.","➤ Use the phrase "+"<b>"+"quarter past"+"</b>"+" when the minute hand completes "+"<b>"+"15 minutes"+"</b>"+" on the dial." + "<br/><br/>➤ Use the phrase "+"<b>"+"half past"+"</b>"+" when the minute hand completes "+"<b>"+"30 minutes"+"</b>"+" on the dial.","➤ Use the phrase "+"<b>"+"to"+"</b>"+" when the minute hand completes between "+"<b>"+"31 to 59 minutes"+"</b>"+" on the dial." + "<br/><br/>➤ Use the phrase "+"<b>"+"quarter to"+"</b>" +" when the minute hand completes "+"<b>"+"45 minutes"+"</b>"+" on the dial."};
   // public static String[] learnClockAnimation_array= {"➤ This is a clock dial.\n\n➤ There are three hands, hour hand, minute hand and second hand on the face of a clock.","➤ This is an hour hand.\n\n➤ The hour hand is a small hand on a clock which shows hours.\n\n➤ When an hour hand completes 24 hours, it's called 1 day.","➤ This is a minute hand.\n\n➤ The minute hand is the long hand on a clock which shows minutes.\n\n➤ When a minute hand completes 60 minutes, it's called 1 hour.","➤ This is a second hand on a clock which shows seconds.\n\n➤ When the second hand completes 60 seconds, it's called 1 minute.","➤ When the minute hand is at the top of the clock at 12, use the phrase O'clock.","➤ Use the phrase past when the minute hand completes between one to 30 minutes on the dial.", "➤ Use the phrase quarter past when the minute hand completes 15 minutes on the dial.\n\n➤ Use the phrase half past when the minute hand completes 30 minutes on the dial.","➤ Use the phrase to when the minute hand completes between 31 to 59 minutes on the dial.\n\n➤ Use the phrase quarter to when the minute hand completes 45 minutes on the dial."};
}


   // static var learnClockAnimation_Array: [String] = [" ➤ " + "This is a clock dial.\n\n" + " ➤ " + "There are three hands, hour hand, minute hand and second hand on the face of a clock.", " ➤ " + "This is an hour hand.\n\n" +  " ➤ " + "The hour hand is a small hand on a clock which shows hours.\n\n" +  " ➤ " + "When an hour hand completes 24 hours, it's called 1 day."," ➤ " + "This is a minute hand.\n\n" + " ➤ " + "The minute hand is the long hand on a clock which shows minutes.\n\n" +  " ➤ " + "When a minute hand completes 60 minutes, it's called 1 hour."," ➤ " + "This is a second hand on a clock which shows seconds.\n\n" + " ➤ " + "When the second hand completes 60 seconds, it's called 1 minute.", " ➤ " + "When the minute hand is at the top of the clock at 12, use the phrase O'clock."," ➤ " + "Use the phrase past when the minute hand completes between one to 30 minutes on the dial.\n" , " ➤ " + "Use the phrase quarter past when the minute hand completes 15 minutes on the dial.\n\n" + " ➤ " + "Use the phrase half past when the minute hand completes 30 minutes on the dial."," ➤ " + "Use the phrase to when the minute hand completes between 31 to 59 minutes on the dial.\n\n" + " ➤ " + "Use the phrase quarter to when the minute hand completes 45 minutes on the dial."

